name: learning_best_packages
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.1
  transparent_image: ^2.0.1
  cached_image: ^0.0.3
  cached_network_image: ^3.2.3
  video_player: ^2.7.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
